#!/usr/bin/env bash
#
# setup-cloudflared.sh — install and configure cloudflared as an outbound-only
# named tunnel that exposes the magpie orchestrator's webhook endpoint to
# GitHub, without opening any inbound port on this host.
#
# This is the production ingress path (PLAN.md Milestone 5), replacing the
# smee.io dev relay. See docs/cloudflared.md for the full runbook and the
# security rationale (HMAC-verified webhook, no Cloudflare Access in front of
# it, orchestrator stays bound to 127.0.0.1).
#
# Usage:
#   MAGPIE_TUNNEL_HOSTNAME=magpie.example.com ./scripts/setup-cloudflared.sh
#   ./scripts/setup-cloudflared.sh magpie.example.com
#   ./scripts/setup-cloudflared.sh --dry-run magpie.example.com
#
# Env vars (all optional except the hostname, which must come from either the
# env var or the first positional argument):
#   MAGPIE_TUNNEL_HOSTNAME   Public hostname to route to the orchestrator.
#                            e.g. magpie.example.com  (REQUIRED — env or $1)
#   MAGPIE_TUNNEL_NAME       cloudflared tunnel name.       (default: magpie)
#   MAGPIE_TUNNEL_SERVICE    Local service the tunnel forwards to.
#                            (default: http://localhost:8787 — the
#                            orchestrator's default bind; see config.toml
#                            [server]. Do NOT point this at anything other
#                            than loopback.)
#   MAGPIE_CLOUDFLARED_USER  Unix user cloudflared will run as / whose
#                            ~/.cloudflared holds cert.pem and the tunnel
#                            credentials file. (default: current user, $USER)
#
# Flags:
#   --dry-run   Print what would be done; make no changes to the system.
#   -h, --help  Show this help and exit.
#
# What this script does NOT do:
#   - It never opens an inbound port. cloudflared only ever makes outbound
#     connections to Cloudflare's edge.
#   - It never runs `cloudflared tunnel login` for you (it's an interactive
#     browser flow) — it detects whether you've already logged in
#     (~/.cloudflared/cert.pem) and tells you the exact command to run if not.
#   - It never commits or prints tunnel credentials. The credentials JSON
#     (~/.cloudflared/<UUID>.json) and cert.pem are secrets generated by the
#     interactive login/create steps; this script only ever references them
#     by path.
#
# Safe to re-run: every step below first checks whether its effect already
# exists (package installed, tunnel already created, DNS route already
# present, config file unchanged) before making a change. An existing
# /etc/cloudflared/config.yml is backed up (timestamped) rather than
# clobbered.

set -euo pipefail

# ---------------------------------------------------------------------------
# Argument / environment parsing
# ---------------------------------------------------------------------------

DRY_RUN=0
POSITIONAL=()

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=1
      ;;
    -h|--help)
      # Print the header comment block above as usage, then exit.
      sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      POSITIONAL+=("$arg")
      ;;
  esac
done

MAGPIE_TUNNEL_HOSTNAME="${MAGPIE_TUNNEL_HOSTNAME:-${POSITIONAL[0]:-}}"
MAGPIE_TUNNEL_NAME="${MAGPIE_TUNNEL_NAME:-magpie}"
MAGPIE_TUNNEL_SERVICE="${MAGPIE_TUNNEL_SERVICE:-http://localhost:8787}"
MAGPIE_CLOUDFLARED_USER="${MAGPIE_CLOUDFLARED_USER:-${USER:-$(id -un)}}"

log()  { printf '[setup-cloudflared] %s\n' "$*" >&2; }
run()  {
  # Run a system-changing command, or just print it under --dry-run.
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN would run: $*"
  else
    log "running: $*"
    "$@"
  fi
}

if [[ -z "$MAGPIE_TUNNEL_HOSTNAME" ]]; then
  log "ERROR: no hostname supplied."
  log "Usage: MAGPIE_TUNNEL_HOSTNAME=magpie.example.com $0"
  log "   or: $0 magpie.example.com"
  exit 1
fi

if [[ "$MAGPIE_TUNNEL_SERVICE" != http://localhost:* && "$MAGPIE_TUNNEL_SERVICE" != http://127.0.0.1:* ]]; then
  log "ERROR: MAGPIE_TUNNEL_SERVICE ('$MAGPIE_TUNNEL_SERVICE') must point at"
  log "loopback (http://localhost:PORT or http://127.0.0.1:PORT). The"
  log "orchestrator binds to 127.0.0.1 by design (see config.toml [server])"
  log "— the tunnel, not the orchestrator, is what makes it reachable from"
  log "the internet. Refusing to route a public hostname anywhere else."
  exit 1
fi

# Resolve the run-as user's home via getent (the passwd database) rather than
# `eval echo ~user`: no shell eval of a username (which could carry special
# characters), and it doubles as an existence check — a typo'd user is caught
# here instead of silently producing a wrong ~/.cloudflared path downstream.
# `|| true`: getent exits non-zero when the user has no passwd entry, which
# under `set -euo pipefail` would abort the script before we can print a
# useful message — swallow it and let the emptiness check below report it.
USER_HOME="$(getent passwd "$MAGPIE_CLOUDFLARED_USER" | cut -d: -f6 || true)"
if [[ -z "$USER_HOME" ]]; then
  log "ERROR: user '$MAGPIE_CLOUDFLARED_USER' does not exist on this system"
  log "(no passwd entry). Set MAGPIE_CLOUDFLARED_USER to the account whose"
  log "~/.cloudflared holds cert.pem and the tunnel credentials file."
  exit 1
fi
CLOUDFLARED_HOME="$USER_HOME/.cloudflared"

log "hostname:        $MAGPIE_TUNNEL_HOSTNAME"
log "tunnel name:     $MAGPIE_TUNNEL_NAME"
log "local service:   $MAGPIE_TUNNEL_SERVICE"
log "run-as user:     $MAGPIE_CLOUDFLARED_USER"
log "cloudflared dir: $CLOUDFLARED_HOME"
[[ "$DRY_RUN" -eq 1 ]] && log "DRY RUN — no changes will be made"

# ---------------------------------------------------------------------------
# 1. Install cloudflared. Works across architectures and distros:
#      - Debian-family hosts (dpkg + apt-get present): Cloudflare's official
#        apt repo, which already selects the right package for whatever
#        architecture `dpkg --print-architecture` reports (amd64, arm64,
#        armhf, ...) — not just arm64/Raspberry Pi.
#      - Everywhere else: the official static `cloudflared` binary from
#        Cloudflare's GitHub releases, matched to `uname -m` and installed
#        only after its SHA256 checksum is verified against the release's
#        published SHA256SUMS.
#    Idempotent: skip entirely if the binary is already present. Fails
#    closed (non-zero exit, no install) on an unrecognized architecture or a
#    checksum mismatch rather than guessing.
# ---------------------------------------------------------------------------

if command -v cloudflared >/dev/null 2>&1; then
  log "cloudflared already installed: $(cloudflared --version 2>&1 | head -n1)"
elif command -v dpkg >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
  log "cloudflared not found; installing from Cloudflare's apt repo (Debian-family host)"

  ARCH="$(dpkg --print-architecture)"
  case "$ARCH" in
    amd64|arm64|armhf|armel|i386) : ;; # packages Cloudflare's apt repo publishes
    *)
      log "WARNING: detected apt architecture '$ARCH'. Cloudflare's apt repo"
      log "selects the right package per-arch via 'dpkg --print-architecture';"
      log "continuing, but verify the install below actually succeeded."
      ;;
  esac

  run sudo mkdir -p --mode=0755 /usr/share/keyrings

  if [[ -f /usr/share/keyrings/cloudflare-main.gpg ]]; then
    log "cloudflare-main.gpg keyring already present, skipping"
  else
    run bash -c \
      'curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
        | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null'
  fi

  CF_APT_LIST=/etc/apt/sources.list.d/cloudflared.list
  if [[ -f "$CF_APT_LIST" ]]; then
    log "$CF_APT_LIST already present, skipping"
  else
    # jammy is used as the stable component name across Debian/Raspberry Pi
    # OS releases per Cloudflare's published instructions; the repo serves
    # arch-appropriate (amd64, arm64, armhf, ...) packages regardless of the
    # codename.
    run bash -c "echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee '$CF_APT_LIST' >/dev/null"
  fi

  run sudo apt-get update
  run sudo apt-get install -y cloudflared

  if [[ "$DRY_RUN" -eq 0 ]]; then
    log "installed: $(cloudflared --version 2>&1 | head -n1)"
  fi
else
  log "cloudflared not found and no apt/dpkg on this host; installing the"
  log "official static binary from Cloudflare's GitHub releases"

  UNAME_M="$(uname -m)"
  case "$UNAME_M" in
    x86_64) CF_ARCH=amd64 ;;
    aarch64|arm64) CF_ARCH=arm64 ;;
    armv7l) CF_ARCH=arm ;;
    *)
      log "ERROR: unsupported architecture '$UNAME_M' for the static"
      log "cloudflared binary. Supported: x86_64, aarch64/arm64, armv7l."
      log "Install cloudflared manually (see docs/ingress.md) and re-run."
      exit 1
      ;;
  esac

  CF_RELEASE_BASE="https://github.com/cloudflare/cloudflared/releases/latest/download"
  CF_BINARY_NAME="cloudflared-linux-${CF_ARCH}"
  CF_TMPDIR="$(mktemp -d)"
  # shellcheck disable=SC2064 # intentionally expand CF_TMPDIR now, not at trap time
  trap "rm -rf '$CF_TMPDIR'" EXIT

  log "downloading $CF_BINARY_NAME and SHA256SUMS from Cloudflare's GitHub releases"
  run curl -fsSL -o "$CF_TMPDIR/$CF_BINARY_NAME" "$CF_RELEASE_BASE/$CF_BINARY_NAME"
  run curl -fsSL -o "$CF_TMPDIR/SHA256SUMS" "$CF_RELEASE_BASE/SHA256SUMS"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN: nothing was downloaded; skipping checksum verification and install"
  else
    EXPECTED_SUM="$(awk -v f="$CF_BINARY_NAME" '$2 == f {print $1}' "$CF_TMPDIR/SHA256SUMS")"
    if [[ -z "$EXPECTED_SUM" ]]; then
      log "ERROR: $CF_BINARY_NAME not listed in the release's SHA256SUMS;"
      log "refusing to install an unverifiable binary."
      exit 1
    fi
    ACTUAL_SUM="$(sha256sum "$CF_TMPDIR/$CF_BINARY_NAME" | cut -d' ' -f1)"
    if [[ "$ACTUAL_SUM" != "$EXPECTED_SUM" ]]; then
      log "ERROR: checksum mismatch for $CF_BINARY_NAME — refusing to install."
      log "  expected: $EXPECTED_SUM"
      log "  actual:   $ACTUAL_SUM"
      exit 1
    fi
    log "checksum verified ($ACTUAL_SUM) — installing to /usr/local/bin/cloudflared"
  fi

  run sudo install -m 0755 "$CF_TMPDIR/$CF_BINARY_NAME" /usr/local/bin/cloudflared

  if [[ "$DRY_RUN" -eq 0 ]]; then
    log "installed: $(cloudflared --version 2>&1 | head -n1)"
  fi
fi

# ---------------------------------------------------------------------------
# 2. Interactive login (browser-based). Cannot be done headlessly — detect
#    whether it has already happened via ~/.cloudflared/cert.pem and, if not,
#    print the exact command and exit with guidance rather than failing hard.
# ---------------------------------------------------------------------------

if [[ -f "$CLOUDFLARED_HOME/cert.pem" ]]; then
  log "cloudflared already authenticated ($CLOUDFLARED_HOME/cert.pem present)"
elif [[ "$DRY_RUN" -eq 1 ]]; then
  # Under --dry-run, cert.pem is expected to be absent (the interactive login
  # hasn't run yet). Don't exit — continue so the operator sees the full plan,
  # with placeholder values standing in for what login/create would produce.
  log "DRY-RUN: cloudflared not yet authenticated ($CLOUDFLARED_HOME/cert.pem"
  log "absent); continuing to show what would be done."
else
  log ""
  log "=========================================================================="
  log "ACTION REQUIRED: cloudflared is not yet authenticated to your Cloudflare"
  log "account. This step opens a browser for you to authorize the tunnel"
  log "against your domain — it cannot be automated headlessly."
  log ""
  log "Run this as $MAGPIE_CLOUDFLARED_USER, then re-run this script:"
  log ""
  log "    cloudflared tunnel login"
  log ""
  log "=========================================================================="
  exit 2
fi

# ---------------------------------------------------------------------------
# 3. Create the named tunnel if it doesn't already exist (idempotent: checked
#    via `cloudflared tunnel list`).
# ---------------------------------------------------------------------------

# Look up the tunnel's UUID by name from `cloudflared tunnel list`. We parse
# the plain-text table (columns: ID  NAME  CREATED  CONNECTIONS) with awk
# rather than `--output json` + python3, so the script carries no implicit
# Python dependency. `$2 == name` matches the NAME column exactly and never
# matches the header row (whose second column is the literal string "NAME").
TUNNEL_UUID=""
if command -v cloudflared >/dev/null 2>&1; then
  TUNNEL_UUID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$MAGPIE_TUNNEL_NAME" '$2 == name {print $1}' || true)"
fi

if [[ -n "$TUNNEL_UUID" ]]; then
  log "tunnel '$MAGPIE_TUNNEL_NAME' already exists (UUID: $TUNNEL_UUID)"
else
  log "tunnel '$MAGPIE_TUNNEL_NAME' not found; creating it"
  run cloudflared tunnel create "$MAGPIE_TUNNEL_NAME"

  if [[ "$DRY_RUN" -eq 0 ]]; then
    TUNNEL_UUID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$MAGPIE_TUNNEL_NAME" '$2 == name {print $1}' || true)"
  else
    TUNNEL_UUID="<TUNNEL-UUID>"
  fi
fi

if [[ -z "$TUNNEL_UUID" ]]; then
  log "ERROR: could not determine the tunnel UUID for '$MAGPIE_TUNNEL_NAME'."
  log "Run 'cloudflared tunnel list' by hand and re-run, or check the create"
  log "step above for errors."
  exit 1
fi

CREDENTIALS_FILE="$CLOUDFLARED_HOME/$TUNNEL_UUID.json"

# ---------------------------------------------------------------------------
# 4. Route the public hostname to this tunnel via a Cloudflare DNS CNAME.
#    Idempotent: `route dns` no-ops (or safely re-confirms) if the record
#    already points at this tunnel.
# ---------------------------------------------------------------------------

log "routing DNS: $MAGPIE_TUNNEL_HOSTNAME -> tunnel $MAGPIE_TUNNEL_NAME"
run cloudflared tunnel route dns "$MAGPIE_TUNNEL_NAME" "$MAGPIE_TUNNEL_HOSTNAME"

# ---------------------------------------------------------------------------
# 5. Render /etc/cloudflared/config.yml from the committed template,
#    substituting hostname / tunnel name / credentials-file path. Back up
#    any existing config rather than clobbering it.
# ---------------------------------------------------------------------------

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="$REPO_ROOT/cloudflared/config.example.yml"
DEST_DIR=/etc/cloudflared
DEST="$DEST_DIR/config.yml"

if [[ ! -f "$TEMPLATE" ]]; then
  log "ERROR: template not found at $TEMPLATE"
  exit 1
fi

RENDERED="$(sed \
  -e "s#^tunnel: .*#tunnel: ${MAGPIE_TUNNEL_NAME}#" \
  -e "s#^credentials-file: .*#credentials-file: ${CREDENTIALS_FILE}#" \
  -e "s#hostname: magpie\.example\.com#hostname: ${MAGPIE_TUNNEL_HOSTNAME}#" \
  -e "s#service: http://localhost:8787#service: ${MAGPIE_TUNNEL_SERVICE}#" \
  "$TEMPLATE")"

run sudo mkdir -p --mode=0755 "$DEST_DIR"

if [[ -f "$DEST" ]]; then
  BACKUP="$DEST.bak.$(date +%Y%m%dT%H%M%S)"
  log "existing $DEST found; backing up to $BACKUP"
  run sudo cp -p "$DEST" "$BACKUP"
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "DRY-RUN would write $DEST with contents:"
  printf '%s\n' "$RENDERED" >&2
else
  printf '%s\n' "$RENDERED" | sudo tee "$DEST" >/dev/null
  sudo chmod 0644 "$DEST"
  log "wrote $DEST"
fi

# ---------------------------------------------------------------------------
# 6. Next steps for the operator.
# ---------------------------------------------------------------------------

log ""
log "=========================================================================="
log "Done. Next steps:"
log ""
log "  1. Review $DEST and confirm the credentials-file path is correct:"
log "       $CREDENTIALS_FILE"
log "  2. Install the committed systemd unit and start the tunnel. The unit"
log "     ships with User=/Group=magpie; set them to the account that owns"
log "     $CLOUDFLARED_HOME (the run-as user, '$MAGPIE_CLOUDFLARED_USER'),"
log "     otherwise cloudflared can't read the credentials file above:"
log "       sudo cp systemd/cloudflared.service /etc/systemd/system/cloudflared.service"
log "       sudo sed -i 's/^User=.*/User=$MAGPIE_CLOUDFLARED_USER/; s/^Group=.*/Group=$MAGPIE_CLOUDFLARED_USER/' /etc/systemd/system/cloudflared.service"
log "       sudo systemctl daemon-reload"
log "       sudo systemctl enable --now cloudflared.service"
log "  3. Point the GitHub App's webhook URL at:"
log "       https://${MAGPIE_TUNNEL_HOSTNAME}/webhook"
log "  4. Verify end-to-end: GitHub App settings -> Advanced -> Recent"
log "     Deliveries -> Redeliver a past delivery -> expect HTTP 200."
log ""
log "See docs/cloudflared.md for the full runbook."
log "=========================================================================="
